### ISSUE TITLE
Add `scripts` to make it easier to bootstrap a development environment locally or in CI

### ISSUE THREAD

**Issue by fwcd** [H1ghBre4k3r/moneyboy-app#30]
Add a set of `scripts` that make it easier to bootstrap a development environment.

For example, `scripts/setup` could be a script that automatically installs npm and Gradle/CocoaPods dependencies. A flag (e.g. `--ci`) could be used to select between `npm ci` and `npm install`. Depending on whether we use iOS (`--ios`) or Android (`--android`), we could also e.g. automatically set up the Xcode development team using

```bash
scripts/setup-xcode-filter [team id]
scripts/recheckout-xcodeproj
```

as introduced in #29.

**Comment by H1ghBre4k3r** [comment]
Closed by #32
